<a href="https://colab.research.google.com/github/Gaurav-Ramachandra/Sem5-BIS_Lab/blob/main/Expt6%2028-11%3A%20Parallel%20Cellular%20Algorithms%20and%20Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def update_state(cell, neighbors):
    """Update the state of the cell based on its neighbors (simple rule)."""
    # Example rule: The cell becomes 1 if it has exactly 3 neighbors, otherwise 0.
    alive_neighbors = sum(neighbors)

    if cell == 1:
        if alive_neighbors < 2 or alive_neighbors > 3:
            return 0  # Dies
        return 1  # Survives
    else:
        if alive_neighbors == 3:
            return 1  # Becomes alive
    return 0  # Stays dead

def get_neighbors(grid, i, j):
    """Get the neighboring cells of grid[i, j] (4 neighbors in 2D grid)."""
    neighbors = []
    rows, cols = grid.shape

    # Check each of the 4 neighbors (up, down, left, right)
    if i > 0: neighbors.append(grid[i-1, j])  # top neighbor
    if i < rows - 1: neighbors.append(grid[i+1, j])  # bottom neighbor
    if j > 0: neighbors.append(grid[i, j-1])  # left neighbor
    if j < cols - 1: neighbors.append(grid[i, j+1])  # right neighbor

    return neighbors

def parallel_cellular_automaton(grid, max_iterations):
    """Simulate the parallel cellular automaton."""
    rows, cols = grid.shape

    for t in range(max_iterations):
        # Create a temporary grid to store updated states
        temp_grid = np.copy(grid)

        # Update each cell in parallel (independently)
        for i in range(rows):
            for j in range(cols):
                neighbors = get_neighbors(grid, i, j)
                temp_grid[i, j] = update_state(grid[i, j], neighbors)

        # Synchronize the grid (copy temp_grid to grid)
        grid = np.copy(temp_grid)

        print(f"Iteration {t+1}:")
        print(grid)

    return grid

# Get user inputs
rows = int(input("Enter number of rows for the grid (e.g., 5): "))
cols = int(input("Enter number of columns for the grid (e.g., 5): "))
max_iterations = int(input("Enter the number of iterations (e.g., 10): "))

# Initialize grid with random states (0 or 1)
grid = np.random.choice([0, 1], size=(rows, cols))

# Print initial grid
print("Initial Grid:")
print(grid)

# Run the parallel cellular automaton simulation
final_grid = parallel_cellular_automaton(grid, max_iterations)

# Final state of the grid
print("Final Grid:")
print(final_grid)


Enter number of rows for the grid (e.g., 5): 5
Enter number of columns for the grid (e.g., 5): 5
Enter the number of iterations (e.g., 10): 10
Initial Grid:
[[0 1 0 1 0]
 [0 0 1 1 0]
 [1 0 1 0 1]
 [0 0 1 0 0]
 [0 0 0 1 0]]
Iteration 1:
[[0 0 1 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 2:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 3:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 4:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 5:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 6:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 7:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 8:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 9:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Iteration 10:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
